In [1]:
import numpy as np

In [2]:
d1 = np.array([1, 2, 3])

In [6]:
d1, d1.shape

(array([1, 2, 3]), (3,))

In [8]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
d2, d2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [12]:
d3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype=float)
d3, d3.shape

(array([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]),
 (1, 3, 3))

In [18]:
x = np.array([[range(1, 100, 10), range(100, 200, 10)]], dtype=float)

In [19]:
x, x.shape

(array([[[  1.,  11.,  21.,  31.,  41.,  51.,  61.,  71.,  81.,  91.],
         [100., 110., 120., 130., 140., 150., 160., 170., 180., 190.]]]),
 (1, 2, 10))

In [20]:
y = np.arange(0, 10, 2)

In [21]:
y, y.shape

(array([0, 2, 4, 6, 8]), (5,))

In [27]:
np.zeros((10, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
d2[0, 2]

np.int64(3)

In [29]:
d3

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [30]:
d3[0, 0, 1]

np.float64(2.0)

In [31]:
d3[0, 1, 1]

np.float64(5.0)

In [32]:
d3[0, 0, 0]

np.float64(1.0)

In [39]:
nums = np.array([1, 2, np.inf], dtype=float)

In [40]:
nums

array([ 1.,  2., inf])

In [42]:
np.isinf(nums).sum()

np.int64(1)

In [43]:
nums2 = np.array([1, 2, np.inf])

In [44]:
nums + nums2

array([ 2.,  4., inf])

In [52]:
nums3 = np.array([1, 2, 3, np.nan, np.inf])

In [53]:
nums3

array([ 1.,  2.,  3., nan, inf])

In [54]:
np.isnan(nums3)

array([False, False, False,  True, False])

In [56]:
np.nan_to_num(nums3, nan=1, posinf=1000)

array([   1.,    2.,    3.,    1., 1000.])

In [57]:
d1, d2, d3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]))

In [58]:
np.mean(d1)

np.float64(2.0)

In [59]:
np.mean(d2)

np.float64(3.5)

In [60]:
np.var(d1)

np.float64(0.6666666666666666)

In [61]:
np.var(d2)

np.float64(2.9166666666666665)

In [62]:
np.var(d3)

np.float64(6.666666666666667)

In [63]:
np.std(d1)

np.float64(0.816496580927726)

In [64]:
np.max(d3)

np.float64(9.0)

In [65]:
np.min(d3)

np.float64(1.0)

In [66]:
np.mean(d2, axis=0)

array([2.5, 3.5, 4.5])

In [69]:
np.min(d3, axis=2)

array([[1., 4., 7.]])

In [70]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
norm = (d2 - np.mean(d2, axis=0)) / np.std(d2, axis=0)
norm

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [78]:
d21 = d2.ravel()

In [79]:
d21

array([1, 2, 3, 4, 5, 6])

In [80]:
d21[0] = 33

In [81]:
d21

array([33,  2,  3,  4,  5,  6])

In [82]:
d2

array([[33,  2,  3],
       [ 4,  5,  6]])

In [84]:
d2.reshape(6, 1)

array([[33],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])

In [85]:
d2.shape

(2, 3)

In [86]:
image = np.random.rand(100, 28, 28)

In [87]:
image

array([[[6.73932098e-01, 2.73979825e-01, 5.88873243e-02, ...,
         6.48266168e-01, 5.41711058e-01, 6.99089548e-01],
        [7.42107176e-01, 2.49109258e-01, 8.21055096e-01, ...,
         7.13760896e-01, 7.44488600e-01, 9.21387344e-01],
        [7.40455064e-01, 5.66026886e-01, 9.48045815e-01, ...,
         5.31778485e-01, 6.91728409e-01, 9.55546320e-02],
        ...,
        [3.79177669e-01, 3.34013612e-01, 7.45333602e-01, ...,
         5.36407696e-01, 9.15761339e-01, 8.06282460e-01],
        [1.47765058e-02, 3.51418502e-01, 5.81282124e-01, ...,
         3.80008316e-01, 7.81429033e-01, 4.59523225e-02],
        [6.97069433e-01, 9.83909166e-01, 5.67837501e-01, ...,
         3.27520588e-02, 8.82261858e-03, 9.28427826e-01]],

       [[1.74245221e-01, 8.12480999e-01, 2.09390204e-01, ...,
         3.30119592e-01, 9.82033398e-01, 9.74900821e-01],
        [1.01265411e-01, 4.81957372e-01, 9.70190333e-01, ...,
         8.21627289e-01, 4.30791609e-01, 5.67706519e-01],
        [8.39440318e-02, 

In [88]:
image_norm = (image - np.mean(image, axis=0)) / np.std(image, axis=0)

In [89]:
image_norm

array([[[ 7.48141159e-01, -8.40277393e-01, -1.55535400e+00, ...,
          6.21975626e-01,  1.08596343e-01,  5.67695261e-01],
        [ 1.00078626e+00, -8.36902066e-01,  1.06769139e+00, ...,
          8.17148060e-01,  8.16713381e-01,  1.51824744e+00],
        [ 8.16804939e-01,  1.67456668e-01,  1.68688276e+00, ...,
          4.50435902e-02,  7.79339207e-01, -1.44277649e+00],
        ...,
        [-3.92562541e-01, -4.98574888e-01,  7.29985233e-01, ...,
          8.36172981e-02,  1.41812756e+00,  1.07831316e+00],
        [-1.46251710e+00, -3.96863416e-01,  2.29544137e-01, ...,
         -4.82361050e-01,  9.74071968e-01, -1.46100803e+00],
        [ 6.86710243e-01,  1.60335757e+00,  1.77438455e-01, ...,
         -1.55508196e+00, -1.56777285e+00,  1.44349791e+00]],

       [[-9.35622923e-01,  1.05379268e+00, -9.88951871e-01, ...,
         -4.97579031e-01,  1.73180398e+00,  1.49849395e+00],
        [-1.31506875e+00, -5.04352753e-02,  1.55388517e+00, ...,
          1.20036524e+00, -3.14531403e

In [90]:
image.shape

(100, 28, 28)

In [91]:
image = image.reshape(100, 28*28)
image

array([[0.6739321 , 0.27397983, 0.05888732, ..., 0.03275206, 0.00882262,
        0.92842783],
       [0.17424522, 0.812481  , 0.2093902 , ..., 0.63711909, 0.48983648,
        0.44613742],
       [0.37501529, 0.8023323 , 0.25245115, ..., 0.56516725, 0.98856692,
        0.70688558],
       ...,
       [0.30159622, 0.29634485, 0.7146327 , ..., 0.27007059, 0.38240651,
        0.59881462],
       [0.81432468, 0.49563235, 0.8554863 , ..., 0.19911558, 0.04272408,
        0.72422081],
       [0.05474194, 0.88674449, 0.67286914, ..., 0.84918678, 0.71452906,
        0.28212151]], shape=(100, 784))

In [96]:
image[99]

array([5.47419422e-02, 8.86744491e-01, 6.72869136e-01, 7.04932587e-01,
       9.92435018e-01, 7.55538256e-01, 1.99324039e-01, 6.50025643e-01,
       6.04939334e-01, 1.16536300e-01, 4.21868774e-01, 1.22528646e-01,
       2.96516941e-01, 9.47042177e-01, 1.46542671e-01, 7.22191585e-01,
       3.16384791e-01, 2.82282659e-01, 6.42712935e-01, 4.07673759e-01,
       7.07835631e-01, 3.26513989e-01, 6.52266698e-01, 6.85496199e-01,
       8.74664357e-01, 6.69384028e-02, 6.47878915e-01, 2.03100377e-01,
       5.06611743e-02, 9.78861383e-01, 9.31091673e-02, 5.12135863e-01,
       1.82791702e-01, 5.77983850e-01, 3.70009384e-01, 3.82818752e-01,
       4.91962998e-01, 6.96533338e-01, 1.36089949e-01, 5.05418520e-01,
       8.60296247e-01, 7.77600120e-01, 4.65471176e-02, 7.37485776e-02,
       1.75879304e-01, 3.80154783e-01, 3.48484390e-01, 6.59166769e-01,
       2.94398313e-01, 1.12230240e-01, 9.33499573e-01, 4.10133721e-01,
       3.40604901e-01, 1.81648747e-01, 2.78478123e-01, 3.88385818e-02,
      

In [97]:
np.arange(0, 9, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9])

In [98]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [99]:
np.repeat(d1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [100]:
np.tile(d1, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [102]:
x = np.random.rand()
x

0.7460461006329867

In [103]:
arr = np.random.rand(10)

In [104]:
arr

array([0.96988875, 0.99702386, 0.41196659, 0.12464754, 0.09383499,
       0.5601655 , 0.8510669 , 0.53885253, 0.88172199, 0.97246804])

In [108]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [113]:
arr = np.arange(0, 50)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [116]:
np.where(arr<11, arr, 0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [117]:
np.argmax(arr)

np.int64(49)

In [118]:
np.argmin(arr)

np.int64(0)

In [121]:
arr = np.arange(0, 50)
arr = arr.reshape(10, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [123]:
np.argmax(np.mean(arr, axis=0))

np.int64(4)

In [124]:
arr[:, np.argmax(np.mean(arr, axis=0))]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [126]:
import os
os.makedirs("data", exist_ok=True)
np.savetxt("data/arr.npy", arr)

In [127]:
arr = np.loadtxt("data/arr.npy")

In [128]:
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

In [133]:
arr1 = np.arange(10, 20)
arr2 = np.arange(30, 40)

In [138]:
np.hstack((arr1, arr2, arr1, arr2))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [137]:
np.vstack((arr1, arr2, arr1, arr2))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [140]:
arr1 = np.random.shuffle(arr1)
arr2 = np.random.shuffle(arr2)

In [145]:
arr1 = np.sort(np.shape(arr1))
arr2 = np.sort(np.shape(arr2))

In [146]:
arr1, arr2

(array([0]), array([], dtype=float64))

In [148]:
a1 = np.array(["2024-09-01", "2026-02-02"], dtype="datetime64")

In [149]:
a1[1]-a1[0]

np.timedelta64(519,'D')

In [150]:
np.arange("2024-09-01", "2026-02-02", dtype="datetime64[D]")

array(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
       '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08',
       '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12',
       '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16',
       '2024-09-17', '2024-09-18', '2024-09-19', '2024-09-20',
       '2024-09-21', '2024-09-22', '2024-09-23', '2024-09-24',
       '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28',
       '2024-09-29', '2024-09-30', '2024-10-01', '2024-10-02',
       '2024-10-03', '2024-10-04', '2024-10-05', '2024-10-06',
       '2024-10-07', '2024-10-08', '2024-10-09', '2024-10-10',
       '2024-10-11', '2024-10-12', '2024-10-13', '2024-10-14',
       '2024-10-15', '2024-10-16', '2024-10-17', '2024-10-18',
       '2024-10-19', '2024-10-20', '2024-10-21', '2024-10-22',
       '2024-10-23', '2024-10-24', '2024-10-25', '2024-10-26',
       '2024-10-27', '2024-10-28', '2024-10-29', '2024-10-30',
       '2024-10-31', '2024-11-01', '2024-11-02', '2024-